services:
  - type: web
    name: growmate-yield-prediction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app_production.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: true
    branch: main
